ITEM.name = "Electrical Components"
ITEM.model = ("models/starwars/syphadias/props/sw_tor/bioware_ea/items/harvesting/scavenge/salvage_wreckage_single.mdl")
ITEM.description = "A set of electrical components"
ITEM.price = 150
ITEM.flag = "a"
ITEM.category = "Misc"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 50
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 1.5