ITEM.name = "Neutronium Barrel"
ITEM.model = ("models/starwars/syphadias/props/sw_tor/bioware_ea/items/harvesting/scavenge/scavenge_barrel.mdl")
ITEM.description = "A barrel of Neutronium."
ITEM.price = 140
ITEM.flag = "a"
ITEM.category = "Misc"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 50
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 1.5