ITEM.name = "Scrap Metal"
ITEM.model = ("models/starwars/syphadias/props/sw_tor/bioware_ea/items/harvesting/scavenge/scavenge_jetsam.mdl")
ITEM.description = "A pile of scrap metal."
ITEM.price = 100
ITEM.flag = "a"
ITEM.category = "Misc"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 5
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 1.5