ITEM.name = "A280c"
ITEM.model = Model("models/weapons/synbf3/w_a280.mdl")
ITEM.description = "The classic rifle used by resistance forces for its all around good stats. Very highly praised by organized and militia forces."
ITEM.category = "Weapons"
ITEM.width = 3 -- Width and height refer to how many grid spaces this item takes up.
ITEM.height = 2
ITEM.flag = "a"
ITEM.price = 60000
ITEM.weight = 1
ITEM.weaponCategory = "primary"
ITEM.class = "tfa_bf2019_a280c"