ITEM.name = "Dawn of Sorrow"
ITEM.model = Model("models/wps_dawnsorrow/wps_dawnsorrow.mdl")
ITEM.description = "The Legendary Dawn of Sorrow sniper rifle."
ITEM.category = "Weapons"
ITEM.width = 4
ITEM.height = 2
ITEM.flag = "a"
ITEM.price = 1000000
ITEM.weight = 5
ITEM.weaponCategory = "primary"
ITEM.class = "tfa_wsp_1"