ITEM.name = "DL-44"
ITEM.model = Model("models/weapons/synbf3/w_dl44.mdl")
ITEM.description = "A classic pistol, wielded by the infamous Han Solo. Packing more power than most other pistols, and it comes with a scope."
ITEM.category = "Weapons"
ITEM.width = 2 -- Width and height refer to how many grid spaces this item takes up.
ITEM.height = 2
ITEM.flag = "a"
ITEM.price = 4000
ITEM.weight = 1
ITEM.weaponCategory = "secondary"
ITEM.class = "tfa_bf2019_dl44"