ITEM.name = "Deathwatch Pistol"
ITEM.model = Model("models/bf2017/w_dlt19.mdl")
ITEM.description = "the deathwatch signature secondary weapon. Has a distinctive sound and packs a whallop."
ITEM.category = "Weapons"
ITEM.width = 3 -- Width and height refer to how many grid spaces this item takes up.
ITEM.height = 2
ITEM.flag = "a"
ITEM.price = 4500
ITEM.weight = 1
ITEM.weaponCategory = "secondary"
ITEM.class = "tfa_deathwatch_1"