ITEM.name = "EE-3"
ITEM.model = Model("models/weapons/synbf3/w_ee3.mdl")
ITEM.description = "Bounty hunter classic. Comes with a nice scope, and can fire in single or a three shot burst."
ITEM.category = "Weapons"
ITEM.width = 3 -- Width and height refer to how many grid spaces this item takes up.
ITEM.height = 2
ITEM.flag = "a"
ITEM.price = 72000
ITEM.weight = 1
ITEM.weaponCategory = "primary"
ITEM.class = "tfa_bf2019_ee3"