ITEM.name = "E-11D"
ITEM.model = Model("models/farena/weapons/w_e-11d.mdl")
ITEM.description = "The E-11D"
ITEM.category = "Weapons"
ITEM.width = 3 -- Width and height refer to how many grid spaces this item takes up.
ITEM.height = 2
ITEM.flag = "a"
ITEM.price = 82000
ITEM.weight = 1
ITEM.weaponCategory = "primary"
ITEM.class = "tfa_e11d_extended"