ITEM.name = "Pantoid Ringer"
ITEM.model = Model("models/papanoidapistol/papanoidapistol.mdl")
ITEM.description = "The pantorans council members weapon of choice when going somewhere that might be unsafe. Comes with a toy bell so your enemies know you mean buisness."
ITEM.category = "Weapons"
ITEM.width = 2
ITEM.height = 2
ITEM.flag = "a"
ITEM.price = 3200
ITEM.weight = 1
ITEM.weaponCategory = "secondary"
ITEM.class = "tfa_papanoid"