ITEM.name = "Recon Pistol"
ITEM.model = Model("models/steelapistol/steelapistol.mdl")
ITEM.description = "A pistol with a scope. Not uncommon, and surprisingly powerful"
ITEM.category = "Weapons"
ITEM.width = 2
ITEM.height = 2
ITEM.flag = "a"
ITEM.price = 900
ITEM.weight = 1
ITEM.weaponCategory = "secondary"
ITEM.class = "tfa_steelapistol"