ITEM.name = "RK-3"
ITEM.model = Model("models/sw_battlefront/weapons/rk3_pistol.mdl")
ITEM.description = "A standard Semi Blaster Pistol."
ITEM.category = "Weapons"
ITEM.width = 2 -- Width and height refer to how many grid spaces this item takes up.
ITEM.height = 1
ITEM.flag = "a"
ITEM.price = 3000
ITEM.weight = 1
ITEM.weaponCategory = "secondary"
ITEM.class = "tfa_bf2019_rk3"