ITEM.name = "Security Pistol"
ITEM.model = Model("models/naboosecurity/naboosecurity.mdl")
ITEM.description = "Nabooan security pistol, formerly used when defending their base, however that has long since been destroyed"
ITEM.category = "Weapons"
ITEM.width = 2
ITEM.height = 2
ITEM.flag = "a"
ITEM.price = 2800
ITEM.weight = 1
ITEM.weaponCategory = "secondary"
ITEM.class = "tfa_naboosecurity"