ITEM.name = "Westar LE"
ITEM.model = Model("models/weapons/w_westar34.mdl")
ITEM.description = "The Westar name, now in a small package. Excels in close range combat"
ITEM.category = "Weapons"
ITEM.width = 2 -- Width and height refer to how many grid spaces this item takes up.
ITEM.height = 1
ITEM.flag = "a"
ITEM.price = 8000
ITEM.weight = 1
ITEM.weaponCategory = "secondary"
ITEM.class = "tfa_752_westar34"