ITEM.name = "Z-6 Rotary"
ITEM.model = Model("models/sw_battlefront/weapons/z6_rotary_cannon.mdl")
ITEM.description = "The heaviest portable weapon in the clone armies arsenal. Capable of unleashing incomparable amounts of damage. This one shoots much faster than others."
ITEM.category = "Weapons"
ITEM.width = 5
ITEM.height = 2
ITEM.flag = "a"
ITEM.price = 1750000
ITEM.weight = 8
ITEM.weaponCategory = "primary"
ITEM.class = "bf2017_z6_summe"