ITEM.name = "Blue Milk"
ITEM.model = "models/neeewpackofprops/jar.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "A high protien milk from a beast, makes you kinda strong"
ITEM.healAmount = 1
ITEM.healSeconds = 3
ITEM.category = "Food"
ITEM.price = 10
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 20
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.05