ITEM.name = "Dire Cat Jerky"
ITEM.model = "models/neeewpackofprops/food20.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "A food for someone on the go and in a hurry to not cook."
ITEM.healAmount = 5
ITEM.healSeconds = 3
ITEM.category = "Food"
ITEM.price = 60
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 10
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.05