ITEM.name = "Hot Cakes"
ITEM.model = "models/neeewpackofprops/food1.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "Dessert that is rather good right out of the oven, mostly with a cherry on top."
ITEM.healAmount = 4
ITEM.healSeconds = 3
ITEM.category = "Food"
ITEM.price = 56
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 5
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.05