ITEM.name = "Sunfruit"
ITEM.model = "models/neeewpackofprops/food24.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "It was used to garnish or enhance dessert dishes."
ITEM.healAmount = 4
ITEM.healSeconds = 3
ITEM.category = "Food"
ITEM.price = 50
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 20
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.03