ITEM.name = "Sausage"
ITEM.model = "models/neeewpackofprops/food29.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "Made mostly of pork and chicken in a lamb casing."
ITEM.healAmount = 5
ITEM.healSeconds = 3
ITEM.category = "Food"
ITEM.price = 30
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 10
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.05