ITEM.name = "Blueprint: Defender Sporting Pistol"
ITEM.model = Model("models/props_lab/clipboard.mdl")
ITEM.description = "A blueprint to build a Defender Sporting Pistol"
ITEM.category = "Recipes"
ITEM.flag = "a"
ITEM.width = 1
ITEM.height = 1
ITEM.blueprint = "defender"
ITEM.price = 4000