ITEM.name = "Bagel Sandwich"
ITEM.model = "models/neeewpackofprops/food31.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "The bagel sandwich is made with cheese and a sausage patty."
ITEM.hungerAmount = 160
ITEM.thirstAmount = 0
ITEM.category = "Food"
ITEM.price = 44
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 5
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.05