ITEM.name = "Cabbage"
ITEM.model = "models/neeewpackofprops/food33.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "Cabbage is a renowned vegetable that is good to eat raw but better boiled."
ITEM.hungerAmount = 60
ITEM.thirstAmount = 0
ITEM.category = "Food"
ITEM.price = 10
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 20
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.03