ITEM.name = "Cooked Meat"
ITEM.model = "models/neeewpackofprops/food28.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "Cooked meat that brings a smile to most."
ITEM.hungerAmount = 200
ITEM.thirstAmount = 0
ITEM.category = "Food"
ITEM.price = 50
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 5
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.05