ITEM.name = "Dough"
ITEM.model = "models/neeewpackofprops/food21.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "Dough is a fluffy mixture of what will make bread in the end after baked."
ITEM.hungerAmount = 40
ITEM.thirstAmount = 0
ITEM.category = "Food"
ITEM.price = 10
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 20
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.05