ITEM.name = "Endwa"
ITEM.model = "models/neeewpackofprops/food11.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "Meat chunks on a stick! Perfect for a meal on the go."
ITEM.hungerAmount = 160
ITEM.thirstAmount = 0
ITEM.category = "Food"
ITEM.price = 40
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 5
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.05