ITEM.name = "Gwamba Fruit"
ITEM.model = "models/neeewpackofprops/food15.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "A fresh fruit, useful for cooking."
ITEM.hungerAmount = 80
ITEM.thirstAmount = 80
ITEM.category = "Food"
ITEM.price = 20
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 20
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.05