ITEM.name = "Ground Meat"
ITEM.model = "models/neeewpackofprops/food26.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "Ground up meat ready to be cooked."
ITEM.hungerAmount = 30
ITEM.thirstAmount = 0
ITEM.category = "Food"
ITEM.price = 10
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 20
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.05