ITEM.name = "Murra Slices"
ITEM.model = "models/neeewpackofprops/food8.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "Slices of meat, usually from the Murra, hence its name. Drissled in a nice sauce"
ITEM.hungerAmount = 220
ITEM.thirstAmount = 0
ITEM.category = "Food"
ITEM.price = 60
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 5
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.05