ITEM.name = "Fruit Stew"
ITEM.model = "models/neeewpackofprops/food2.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "Bungle of fruits with a broth of delicacy, sweet and salty a perfect mix."
ITEM.hungerAmount = 180
ITEM.thirstAmount = 100
ITEM.category = "Food"
ITEM.price = 30
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 5
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.05