ITEM.name = "Salthia Beans"
ITEM.model = "models/neeewpackofprops/food24.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "A great food to add with rice."
ITEM.hungerAmount = 80
ITEM.thirstAmount = 0
ITEM.category = "Food"
ITEM.price = 24
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 10
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.03