ITEM.name = "Yako Root"
ITEM.model = "models/neeewpackofprops/food15.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.description = "A root vegetable, useful for cooking."
ITEM.hungerAmount = 40
ITEM.thirstAmount = 0
ITEM.category = "Food"
ITEM.price = 10
ITEM.flag = "a"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 20
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.05